apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: qwen2-predictor-autoscaler
  namespace: kubeflow
spec:
  maxReplicaCount: 5
  scaleTargetRef:
    name: qwen2-predictor    # update if your Deployment name differs
    apiVersion: apps/v1
    kind: Deployment
  pollingInterval: 5
  cooldownPeriod: 10
  minReplicaCount: 1
  triggers:
    - type: prometheus
      metadata:
        metricName: vllm:num_requests_running{model_name="Qwen/Qwen2.5-0.5B-Instruct"}
        threshold: '2'
        serverAddress: "http://prometheus-service.kubeflow.svc.cluster.local:8080"
        # query should aggregate across pods; user provided `vllm:num_requests_running` and noted averaging
        query: avg(vllm:num_requests_running)
        #If your metric name is different (contains a colon) replace the above query accordingly.