apiVersion: serving.kserve.io/v1alpha1
kind: LocalModelNodeGroup
metadata:
  name: workers
spec:
  storageLimit: 50G
  persistentVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50G
    storageClassName: standard
    volumeMode: Filesystem
    volumeName: models
  persistentVolumeSpec:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    capacity:
      storage: 50G
    local:
      path: /models
    storageClassName: standard

---
apiVersion: serving.kserve.io/v1alpha1
kind: LocalModelCache
metadata:
  name: qwen2.5-0.5b-instruct-cache
spec:
  sourceModelUri: 'hf://Qwen/Qwen2.5-0.5B-Instruct'
  modelSize: 10Gi
  nodeGroups:
    - workers
